# Generated by Django 4.1.5 on 2023-06-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_banner',
        ),
    ]
