# Generated by Django 4.1.5 on 2023-06-29 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_poll_discription_remove_poll_intro_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_info',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=200)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_office', to='polls.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=250)),
                ('personal_image', models.ImageField(upload_to='media/candidates')),
                ('votes', models.PositiveIntegerField()),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_office', to='polls.office')),
            ],
        ),
    ]
