# Generated by Django 4.1.5 on 2023-06-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_poll_info_office_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
