# Generated by Django 4.1.5 on 2023-06-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_candidate_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_candidate', to='polls.poll'),
        ),
    ]
