# Generated by Django 4.1.5 on 2023-06-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_candidate_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='cost',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='poll',
            name='location',
            field=models.CharField(default='default text', max_length=50),
        ),
    ]
