# Generated by Django 4.1.5 on 2023-07-12 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_cost_poll_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('verification_status', models.BooleanField(default=False)),
                ('date_of_transaction', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=300, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.candidate')),
            ],
            options={
                'ordering': ['-date_of_transaction'],
            },
        ),
    ]
