# Generated by Django 4.1.5 on 2023-07-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='verification_status',
            new_name='transaction_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='votes',
            field=models.PositiveIntegerField(default=2222),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
