# Generated by Django 4.1.5 on 2023-07-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_rename_verification_status_payment_transaction_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='token',
        ),
    ]
