# Generated by Django 4.1.5 on 2023-07-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_candidate_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=30)),
                ('used', models.BooleanField(default=False)),
                ('time_used', models.DateTimeField(null=True)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_coupon', to='polls.poll')),
            ],
        ),
    ]
