# Generated by Django 4.1.5 on 2023-07-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_votingcoupons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VotingCoupons',
            new_name='VotingCoupon',
        ),
    ]
