# Generated by Django 4.1.5 on 2023-08-29 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_rename_votingcoupons_votingcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='personal_image',
            field=models.ImageField(upload_to='candidates'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='cost',
            field=models.PositiveIntegerField(choices=[('50', 50), ('100', 100), ('200', 200), ('500', 500), ('1000', 1000)], default=100),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_image',
            field=models.ImageField(upload_to='poll'),
        ),
        migrations.CreateModel(
            name='couponPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_coupons', models.PositiveIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('reference', models.CharField(max_length=200, null=True)),
                ('verification', models.BooleanField(default=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_coupon_payment', to='polls.poll')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
