# Generated by Django 4.1.5 on 2023-09-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_poll_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='cost',
            field=models.PositiveIntegerField(choices=[(50, '50'), (100, '100'), (200, '200'), (500, '500'), (1000, '1000')], default='100'),
        ),
    ]
