# Generated by Django 4.1.5 on 2023-10-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_poll_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_office', to='polls.office'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_candidate', to='polls.poll'),
        ),
        migrations.AlterField(
            model_name='couponpayment',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_coupon_payment', to='polls.poll'),
        ),
        migrations.AlterField(
            model_name='emailpayment',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.candidate'),
        ),
        migrations.AlterField(
            model_name='office',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_office', to='polls.poll'),
        ),
        migrations.AlterField(
            model_name='votingcoupon',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_coupon', to='polls.poll'),
        ),
        migrations.CreateModel(
            name='PollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('reference', models.CharField(max_length=200, null=True)),
                ('verification', models.BooleanField(default=False)),
                ('transaction_time', models.DateTimeField()),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_payment', to='polls.poll')),
            ],
        ),
    ]
