# Generated by Django 4.1.5 on 2023-10-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_poll_active_alter_candidate_office_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollpayment',
            name='poll',
        ),
        migrations.AddField(
            model_name='poll',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_payment', to='polls.pollpayment'),
        ),
        migrations.AlterField(
            model_name='pollpayment',
            name='amount',
            field=models.PositiveIntegerField(default=1000, null=True),
        ),
    ]
