# Generated by Django 4.1.5 on 2023-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_remove_pollpayment_poll_poll_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='payment',
        ),
        migrations.AddField(
            model_name='poll',
            name='payment_ref',
            field=models.CharField(default='no ref', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pollpayment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='pollpayment',
            name='reference',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pollpayment',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
