# Generated by Django 4.1.5 on 2023-11-11 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0019_remove_poll_payment_poll_payment_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='payment_ref',
        ),
        migrations.AddField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_payment', to='polls.pollpayment'),
        ),
    ]
