# Generated by Django 4.1.5 on 2023-02-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='status',
            field=models.CharField(choices=[('customer', 'customer'), ('staff', 'staff'), ('admin', 'admin')], default='customer', max_length=50),
        ),
    ]
