# Generated by Django 4.1.5 on 2023-02-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_myusers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='password2',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
