# Generated by Django 4.1.5 on 2023-02-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_myusers_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='password2',
        ),
    ]
