# Generated by Django 4.1.5 on 2023-02-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_myusers_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verification', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='myusers',
            name='email_verification',
        ),
        migrations.AddField(
            model_name='myusers',
            name='ucccdd',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
