# Generated by Django 4.1.5 on 2023-02-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_remove_myusers_email_verification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='ucccdd',
        ),
        migrations.AddField(
            model_name='myusers',
            name='email_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
